server:
  servlet:
    context-path: /game

spring:
  profiles:
    active: prd
  application:
    name: wx-game-admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 30000
    min-idle: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    bySearch:
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 18800
    time-between-eviction-runs-millis: 18800
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件大小
      max-request-size: 99MB # 设置总上传的数据大小
      enabled: true #开启
  jackson:
    time-zone: GMT+8
#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 2 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false